FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:edge

RUN apt-get update && apt-get install -y \
    libappindicator3-dev \
    libgtk-3-dev \
    libdbus-1-dev \
    libsecret-1-dev \
    && rm -rf /var/lib/apt/lists/*
